<?php

/**
 * Write resources/data/removed-files.php: the files Tallport's history had
 * that the current tree doesn't, each with every version (git blob SHA-1) it
 * had. System > Status > Files deletes such a file when it is byte for byte
 * one of them (App\Misc\FileCheck). Folders the updater replaces as a whole
 * (FileCheck::REPLACED_FOLDERS) can't hold leftovers and are left out.
 *
 *   php dev/removed-files.php          regenerate the list
 *   php dev/removed-files.php --check  fail if the committed list is stale (release-check.sh)
 */
chdir(dirname(__DIR__));
require 'vendor/autoload.php';

$target = 'resources/data/removed-files.php';

$git = function ($command) {
    exec('git '.$command, $output, $exit_code);
    if ($exit_code !== 0) {
        fwrite(STDERR, "git $command failed\n");
        exit(1);
    }

    return implode("\n", $output);
};

$current = array_flip(explode("\0", $git('ls-tree -r -z --name-only HEAD')));

// Every change of every commit since the first (FreeScout's import): ":old_mode new_mode old_sha new_sha status\0path\0".
$fields = explode("\0", $git('log --root --no-renames --no-abbrev --format= --raw -z HEAD'));
$removed = [];
for ($i = 0; $i < count($fields) - 1; $i++) {
    $change = preg_split('#\s+#', trim($fields[$i]));
    if (!str_starts_with($change[0], ':') || count($change) < 5) {
        continue;
    }
    $path = $fields[++$i];
    if (isset($current[$path]) || in_array(explode('/', $path)[0], App\Misc\FileCheck::REPLACED_FOLDERS)) {
        continue;
    }
    foreach ([$change[2], $change[3]] as $sha) {
        if (!preg_match('#^0+$#', $sha)) {
            $removed[$path][$sha] = true;
        }
    }
}
ksort($removed, SORT_STRING);

$php = "<?php\n\n// Generated by `php dev/removed-files.php`: files earlier releases shipped, with each\n// version's git blob SHA-1 (App\\Misc\\FileCheck's leftovers). Don't edit.\nreturn [\n";
foreach ($removed as $path => $shas) {
    $shas = array_keys($shas);
    sort($shas);
    $php .= '    '.var_export($path, true).' => [\''.implode('\', \'', $shas)."'],\n";
}
$php .= "];\n";

if (in_array('--check', $argv)) {
    if (@file_get_contents($target) !== $php) {
        fwrite(STDERR, "$target is stale: run php dev/removed-files.php and commit it\n");
        exit(1);
    }
    echo "$target is up to date\n";
    exit(0);
}

if (!is_dir(dirname($target))) {
    mkdir(dirname($target), 0755, true);
}
file_put_contents($target, $php);
echo 'Wrote '.count($removed)." files to $target\n";
